'use client';
import type { Metadata } from "next";
import { useRouter, usePathname } from "next/navigation";
import { Inter } from "next/font/google";
import Script from "next/script";
import "../../globals.css";


import TopNav from "../../UI/TopNav";
import SideNav from "../../UI/SideNav";
import Footer from "../../UI/Footer";
import { useEffect, useState } from "react";
import LoadingBar from 'react-top-loading-bar';
import pageLoading from '../../UI/PageLoading';
import { LoadingIndicator } from '../../UI/LoadingIndicator';
const inter = Inter({ subsets: ["latin"] });

/*
export const metadata: Metadata = {
  title: "Users",
  description: "Generated by create next app",
  keywords: "Saurabh-"
};
/**/
export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  const [user, setUser] = useState(null);
  const [key, setKey] = useState(0);
  const [progress, setProgress] = useState(0);
  const router = useRouter();
  const pathname = usePathname();
  const p = pageLoading();
  useEffect(() => {
    console.log(pathname);
    const token: any = localStorage.getItem('token');
    if (token != null) {
      setUser(token);
      setKey(Math.random());
    }
    //pageLoading();

  }, []);
  const logOut = () => {
    console.log('user log out successfully.')
    localStorage.removeItem('token');
    setUser(null);
    setKey(Math.random());

  }
  return (
    <html lang="en">
      <>
        <Script src="/main.js" strategy="lazyOnload"></Script>
        <body className={inter.className}>
          <LoadingIndicator></LoadingIndicator>
          <LoadingBar
            color='#f11946'
            progress={progress}
            onLoaderFinished={() => setProgress(0)}
          />
          <main className="flex min-h-screen flex-col p-3">
            <TopNav user={user} key={key} logout={logOut}></TopNav>
            <div className="mt-4 flex grow flex-col gap-4 md:flex-row">
              <div className="flex flex-col justify-left gap-6 rounded-lg bg-purple-200 px-6 py-1 md:w-1/5 md:px-1">


                <SideNav></SideNav>


              </div>

              {children}

            </div>
            {<Footer></Footer>}

          </main>
        </body>

      </>
    </html>
  );
}

