
import type { Metadata } from "next";

import { Inter } from "next/font/google";
//import "../../globals.css";
import '@/app/globals.css';
import SessionWrapper from "./components/sessionWrapper";
import SideNav from "./components/UI/SideNav";
import TopNav from "./components/UI/TopNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next Auth app",
  description: "Generated by create next app",
  keywords: "Saurabh"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <SessionWrapper><body className={inter.className}>
        <main className="flex min-h-screen flex-col p-3">
          <TopNav></TopNav>
          <div className="mt-4 flex grow flex-col gap-4 md:flex-row">
            <div className="flex flex-col justify-left gap-6 rounded-lg bg-purple-200 px-6 py-1 md:w-1/5 md:px-1">


              <SideNav></SideNav>


            </div>

            {children}
          </div>

          <footer></footer>
        </main>
      </body></SessionWrapper>
    </html>
  );
}
