
import type { Metadata } from "next";

import { Inter } from "next/font/google";
import Script from "next/script";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Users",
  description: "Generated by create next app",
  keywords: "Saurabh-"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <>
        <Script src="/main.js" strategy="lazyOnload"></Script>
        <body className={inter.className}>{children}</body>

      </>
    </html>
  );
}
